### ISSUE TITLE
12.03 실습(useEffect, Local Storage, CRUD, todo, css 모듈)

### ISSUE THREAD

**Issue by kyung412** [kyung412/goorm_study#9]
**[목표]**
저번 시간에 다하지 못했던 useEffect에 대한 내용 이어서 학습하고, 
이번 수업 시간에 다룬 내용의 개념을 정리하면서 투두리스트를 실습을 통해
다시 한번 되짚어 보는 시간을 가지는 것을 목표로 활동을 시작했다.

**[오늘의 활동]**
학습1. useEffect, 로컬 스토리지
학습2. CRUD개념과 투두리스트 코드 분석 및 실습
학습3. 투두리스트 css 반영(전역, 모듈)

**Comment by kyung412** [comment]
### [useEffect]
`useEffect`: 리액트 컴포넌트의 `SideEffect`를 제어하는 hook
`SideEffect`: 어떠한 동작에 따른 "부수적인 효과", "파생되는 효과"

**[useEffect 구조]**
<img width="331" alt="image" src="https://github.com/user-attachments/assets/2b749ef3-63c0-43b2-ab8a-af0a5b071029">

**[의존성 배열(dependencies array)]**
dep : `useEffect`의 실행되는 조건을 제어하며, 특정 값이 변경될 때만 `useEffect`가 실행되도록 설정함.

**1. 의존성 배열 생략** :컴포넌트가 렌더링 될때마다 `useEffect`가 매번 실행(App.jsx)
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/0574524c-e01f-4a6c-a91a-5c9277529e5e">

_*마운트(Mount) : 컴포넌트가 처음에 나타나는 과정_
_*언마운트(Unmount) : 컴포넌트가 화면에서 사라질 때의 과정_

**2. 특정 값이 포함된 배열** : 배열 안의 값이 변경될 때마다 `useEffect`가 실행(App2.jsx)
<img width="1161" alt="image" src="https://github.com/user-attachments/assets/06dadb64-dcc8-48a9-a2a9-af53478122b6">

_*업데이트(Update) : 컴포넌트의 상태(state)나 속성(props)가 변경될 때 리렌더링_
→count가 변경될 때마다 `useEffect`가 실행되며 최신의 count값을 출력(update)

**3. 빈배열([])** : 마운트시 한번만 실행(App3.jsx)
<img width="1099" alt="image" src="https://github.com/user-attachments/assets/446d78a6-6937-4dc6-95fd-d7e7567c9f9a">

→컴포넌트 초기화 : `useEffect`가 실행되며 컴포넌트가 처음 렌더링 될때 한번만 API를 호출
→데이터 가져오기 : `fetch`로 네트워크 요청보내고, 응답을 JSON 형식으로 파싱
→상태 업데이트 :  파싱된 데이터를 `setData`로 React 상태 저장
→리렌더링 : 상태가 변경되면 컴포넌트 다시 렌더링되며, 가져온 데이터(`data.title`)가 화면에 표시됨

**[정리 작업]**
정리작업은 메모리 누수를 방지하고 불필요한 작업을 중단하는 역할을 하며,
주로 타이머 해제, 이벤트 리스너 제거, 구독 취소 등에 사용됨

<img width="1504" alt="image" src="https://github.com/user-attachments/assets/8d829e2f-5901-4f3c-9f7f-644803c9bc24">

1. 초기화
→App4.jsx의 `showTimer`는 초기값이 `true`이므로 `Timer` 컴포넌트가 렌더링
→Timer.jsx의 `useEffect`가 실행되어 타이머가 시작
2. 타이머 작동 
→`time` 값이 1초마다 증가하고 화면에 갱신 →콘솔에는 `"Timer started"`가 출력
3. Remove Timer 버튼 클릭
→`showTimer`가 `false`로 변경되어 `Timer`컴포넌트가 화면에서 제거
→`Timer`의 `useEffect` 정리 작업이 실행되어 `clearInterval`로 타이머가 해제
→콘솔에는 `"Timer cleared"`가 출력
4. Show Timer 버튼 클릭
→`showTimer`가 다시 `true`로 변경되어 `Timer` 컴포넌트가 다시 렌더링 →타이머가 새로 시작

### [Local Storage]

**로컬 스토리지(Local Storage)** : 웹 브라우저가 제공하는 클라이언트 측 저장소로, 사용자가 데이터를 로컬(사용자의 브라우저) 환경에 저장하고 필요할 때 불러올 수 있는 기능

**[특징]**
1. 클라이언트 측 저장소 : 데이터를 브라우저에 저장하며, 서버에 요청하지 않아도 데이터 관리 가능
5. 영구저장 : 사용자가 브라우저의 캐시를 삭제하거나 명시적으로 데이터를 제거하지 않는 이상, 저장된 데이터는 브라우저를 닫거나 pc를 재부팅해도 사라지지 않음
6. **키(key)-값(value)구조** 
    * **데이터를 고유한 키로 식별하여, 값은 문자열 형태로 저장**
    * 숫자, 배열, 객체 등을 저장하려면 **JSON으로 문자열 변환**(`JSON.stringify`)이 필요함
7. 용량 제한 : 브라우저마다 다르지만, 일반적으로 약 5~10MB로 제한하므로 대용량 데이터에는 부적합
8. 보안 : 브라우저에서 로컬로 데이터를 저장하기 때문에 보안에 취약하므로 민감한 정보는 저장하지 않는게 좋음

**[사용]** : JS의 `localstorage`객체를 사용하여 접근
1. **데이터 저장** : `localStorage.setItem("key", "value");`

3. **데이터 가져오기** 
```
const value = localStorage.getItem("key");
console.log(value); 
```
4. **데이터 삭제**
- 특정 데이터 삭제 : `localStorage.removeItem("key");`
- 모든 데이터 삭제 : `localStorage.clear();`

5. **저장된 키 확인**
```
const key = localStorage.key(0); 
console.log(key);
```
6. **저장된 데이터 개수 확인**
```
const count = localStorage.length;
console.log(count);
```

**Comment by kyung412** [comment]
### [CRUD의 개념과 투두리스트 ]
CRUD는 데이터의 기본적인 작업을 설명하는 약어로, Create, Read, Update, Delete의 줄임말
<img width="748" alt="image" src="https://github.com/user-attachments/assets/0f4e616a-59d7-4b44-a093-e82ef0744caa">


### Create (생성) : 새로운 데이터를 추가하는 작업

🔍 사용자가 새로운 할일을 입력하고 추가

- `App.jsx`에서 `addTodo`함수로 구현
- `TodoInput.jsx`에서 호출
→사용자가 텍스트를 입력하고 "Enter"를 누르거나, "등록"버튼 클릭시 `addTodo `호출
→새로운 할 일은 상태(`todos`)에 추가되고, 로컬 스토리지에도 저장됨
<img width="239" alt="image" src="https://github.com/user-attachments/assets/2606d6cb-6eb2-4984-98c0-7eddcd3f54f7">

### Read (읽기) : 저장된 데이터를 조회하거나 검색하는 작업

🔍 저장된 데이터를 로컬 스토리지에서 읽고 화면에 렌더링
- `App.jsx`에서 로컬 스토리지 데이터를 초기화
- `TodoList.jsx`에서 할 일 목록을 화면에 출력  
→로컬 스토리지에서 데이터를 가져와 상태를 초기화
→할 일 목록은 `TodoList`에서 `TodoItem` 컴포넌트로 하나씩 보여줌
<img width="439" alt="image" src="https://github.com/user-attachments/assets/f856d8a5-05b3-4800-9c85-d16149838688">

### Update (수정) : 기존 데이터를 수정하거나 갱신하는 작업

🔍 텍스트 수정과 완료 상태 변경 기능을 제공
- `App.jsx`에서 수정(`updateTodo`)와 완료 상태 변경(`toggleComplete`)함수로 구현
- `TodoItem.jsx`에서 호출
→수정 모드에서 사용자가 내용을 변경하면 `updateTodo`가 호출되어 상태를 업데이트
→체크박스를 클릭하면 완료 상태가 변경됨(`toggleComplete`)
<img width="390" alt="image" src="https://github.com/user-attachments/assets/3e71c3ff-cfee-487e-a9eb-82aa9d6e7559">

### Delete (삭제) : 저장된 데이터를 삭제하는 작업

🔍 특정 할일을 제거하며 상태와 화면을 동기화
- `App.jsx`에서 `deleteTodo`함수로 구현
- `TodoItem.jsx`에서 호출
→사용자가 삭제 버튼을 클릭하면, 해당 할 일이 `todos`상태에서 제거됨
→변경된 상태는 로컬 스토리지에도 자동 반영됨  
<img width="353" alt="image" src="https://github.com/user-attachments/assets/3eaf958a-67fb-4d3e-8451-29964330b781">

### [투두리스트 실습]
<img width="1311" alt="image" src="https://github.com/user-attachments/assets/79c54759-b538-48e3-aa76-578c3e6b1cf9">

- [x] 1. 함수 실행 여부 확인(useState, useEffect, addTodo)
- [x] 2. Application의 storage에서 내용 등록 확인
- [x] 3. Todos 키 안에 배열을 할당 여부
- [x] 4. 할당된 그 배열안에 방금 입력한 내용으로 객체 등록 되는지 여부 확인
- [x] 5.  객체 안에 3개의 값이 명확하게 등록되었는지 여부(completed, id, text)

**Comment by kyung412** [comment]
### [전역 CSS와 CSS모듈]

**[전역 CSS]**
* 적용 범위: 프로젝트 전체에 영향을 미치는 스타일.
* 사용 목적: 초기 설정, 공통 폰트, 테마(다크/라이트 모드), 레이아웃 정의.
* 사용 파일: `Index.css`, `App.module.css`
* ex : body, h1, button 같은 기본 태그 스타일.
_*Index.css(애플리케이션 전역) *App.css(App 컴포넌트와 관련된 스타일)_

**[CSS 모듈]**
* 적용 범위: 특정 컴포넌트에만 고유한 스타일 적용.
* 사용 목적: 스타일 충돌 방지, 독립적인 스타일링.
* 사용 파일: `TodoInput.module.css`, `TodoList.module.css`
* ex: TodoInput, TodoList 컴포넌트에만 스타일 적용.

### [회고]
저번 시간에 부족했던 부분 학습하고, 오늘은 수업자료를 토대로 
기본적인 투두리스트를 분석 및 생성하는 시간을 가졌다. 
다음 시간은 CRUD의 기능에 대해 다시 복습하고, CSS부분은 조금씩 코드 변경해보면서 실습해봐야 할 것 같다..

**Comment by RunaUXLabs** [comment]
CRUD 샘플코드를 보고 내가 알고 있는 개념과 매칭했을 때 술술 읽히는 것 까지를 목표로 잡으면 됩니다.
계속 반복해서 익히는게 중요해요.
익숙해지면 코드 변형이나 기능 추가, UI 변경 시도까지 달릴 수 있습니다.
차근차근 디벨롭 해봅시다!💪
